// Generated by https://quicktype.io

export interface ICreateProductResponse {
    message: string;
    product: ICreateProduct;
}

export interface ICreateProduct {
    name:        string;
    description: string;
    stock:       number;
    price:       number;
    category_id: number;
    slug:        string;
    updated_at:  string;
    created_at:  string;
    id:          number;
}
