// Generated by https://quicktype.io

export interface IFullProductResponse {
    product: IFullProduct;
}

export interface IFullProduct {
    id:          number;
    name:        string;
    description: string;
    stock:       number;
    slug:        string;
    price:       number;
    image:       string;
    category:    Category;
    createdAt:   string;
}

interface Category {
    id:   number;
    name: string;
    slug: string;
}
